from django.db import models

# Create your models here.
class MyModel(models.Model):
    # auto_field = models.AutoField(primary_key=True)
    big_auto_field = models.BigAutoField(primary_key=True)
    big_integer_field = models.BigIntegerField()
    binary_field = models.BinaryField()
    boolean_field = models.BooleanField()
    char_field = models.CharField(max_length=255)
    date_field = models.DateField()
    date_time_field = models.DateTimeField()
    decimal_field = models.DecimalField(max_digits=5, decimal_places=2)
    duration_field = models.DurationField()
    file_field = models.FileField(upload_to='files/')
    # file_path_field = models.FilePathField(path='/path/to/files/')
    generic_ip_address_field = models.GenericIPAddressField()
    json_field = models.JSONField()
    # many_to_many_field = models.ManyToManyField()
    null_boolean_field = models.BooleanField(null=True)
    # one_to_one_field = models.OneToOneField(OtherModel, on_delete=models.CASCADE)
    positive_big_integer_field = models.PositiveBigIntegerField()
    positive_small_integer_field = models.PositiveSmallIntegerField()
    slug_field = models.SlugField()
    small_integer_field = models.SmallIntegerField()
    # text_field = models.TextField()
    time_field = models.TimeField()
    time_field = models.TimeField()
    uuid_field = models.UUIDField()
